### ISSUE TITLE
How to cite jtorch?

### ISSUE THREAD

**Issue by hughperkins** [jonathantompson/jtorch#3]

**Comment by jonathantompson** [comment]
Hmmmm... I'm not sure actually.  It was used for this paper:

http://yann.lecun.com/exdb/publis/pdf/tompson-siggraph-14.pdf

But I didn't mention it there. So maybe just something like:

@online{jtorch,
  author = {Jonathan Tompson},
  title = {JTorch OpenCL utility library},
  url = {https://github.com/jonathantompson/jtorch}
}

I trust your judgement though, whatever you think works :-)

**Comment by hughperkins** [comment]
Thanks.  I'm just using normal bibtex, so I've put:

```
@misc{jtorch,
  author = {Jonathan Tompson},
  title = {JTorch OpenCL utility library},
  howpublished = {\url{https://github.com/jonathantompson/jtorch}},
  note = {Accessed: 2016-05-14}
}
```

**Comment by hughperkins** [comment]
well... reversed order of author names:

```
@misc{jtorch,
  author = {Tompson, Jonathan},
  title = {JTorch OpenCL utility library},
  howpublished = {\url{https://github.com/jonathantompson/jtorch}},
  note = {Accessed: 2016-05-14}
}
```

**Comment by hughperkins** [comment]
(yay, I have a whole page of references now.  If I keep going I wont have to actually write anything :-D )

**Comment by hughperkins** [comment]
(Observation "utility" is pretty vague.  I'd be tempted just to leave it at JTorch, or change 'utility' to 'prediction'?  It changes nothing for me particularly, just something that occurred to me...)
